# Generated by Django 5.0.7 on 2025-05-27 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='User_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
